@startuml
'https://plantuml.com/sequence-diagram

title Update Recipe
autonumber
participant app
participant "ms-cook-love" as mcl
database "cook-db" as db

app -> mcl: click Edit icon: PUT /api/v1/recipe
mcl -> db: save request payload to t_recipe
db -> mcl: return success
mcl -> app: return updated recipe

@enduml